"""deleted abbreviation table and added short_name to subject

Revision ID: 012ccbc70ffe
Revises: 354d93a6d444
Create Date: 2024-11-06 01:32:08.346189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012ccbc70ffe'
down_revision: Union[str, None] = '354d93a6d444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('short_name', sa.String(length=25), nullable=False))
    op.drop_constraint('subjects_abbreviation_id_fkey', 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'abbreviation_id')
    op.drop_table('abbreviations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('abbreviation_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('subjects_abbreviation_id_fkey', 'subjects', 'abbreviations', ['abbreviation_id'], ['id'])
    op.drop_column('subjects', 'short_name')
    op.create_table('abbreviations',
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='abbreviations_pkey'),
    sa.UniqueConstraint('name', name='abbreviations_name_key'),
    sa.UniqueConstraint('short_name', name='abbreviations_short_name_key')
    )
    # ### end Alembic commands ###
