"""changed abbreviation name and short_name max length

Revision ID: 354d93a6d444
Revises: f2972392367d
Create Date: 2024-11-05 20:56:52.987605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354d93a6d444'
down_revision: Union[str, None] = 'f2972392367d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('abbreviations', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('abbreviations', 'short_name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('abbreviations', 'short_name',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('abbreviations', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
